export const pieces = {
  "0:0": require("../assets/wr.png"),
  "0:1": require("../assets/wn.png"),
  "0:2": require("../assets/wb.png"),
  "0:3": require("../assets/wk.png"),
  "0:4": require("../assets/wq.png"),
  "0:5": require("../assets/wb.png"),
  "0:6": require("../assets/wn.png"),
  "0:7": require("../assets/wr.png"),

  "1:0": require("../assets/wp.png"),
  "1:1": require("../assets/wp.png"),
  "1:2": require("../assets/wp.png"),
  "1:3": require("../assets/wp.png"),
  "1:4": require("../assets/wp.png"),
  "1:5": require("../assets/wp.png"),
  "1:6": require("../assets/wp.png"),
  "1:7": require("../assets/wp.png"),

  "7:0": require("../assets/br.png"),
  "7:1": require("../assets/bn.png"),
  "7:2": require("../assets/bb.png"),
  "7:3": require("../assets/bq.png"),
  "7:4": require("../assets/bk.png"),
  "7:5": require("../assets/bb.png"),
  "7:6": require("../assets/bn.png"),
  "7:7": require("../assets/br.png"),

  "6:0": require("../assets/bp.png"),
  "6:1": require("../assets/bp.png"),
  "6:2": require("../assets/bp.png"),
  "6:3": require("../assets/bp.png"),
  "6:4": require("../assets/bp.png"),
  "6:5": require("../assets/bp.png"),
  "6:6": require("../assets/bp.png"),
  "6:7": require("../assets/bp.png"),
};

export const piecesConstants = {
  "0:0": "w",
  "0:1": "w",
  "0:2": "w",
  "0:3": "w",
  "0:4": "w",
  "0:5": "w",
  "0:6": "w",
  "0:7": "w",

  "1:0": "w",
  "1:1": "w",
  "1:2": "w",
  "1:3": "w",
  "1:4": "w",
  "1:5": "w",
  "1:6": "w",
  "1:7": "w",

  "7:0": "b",
  "7:1": "b",
  "7:2": "b",
  "7:3": "b",
  "7:4": "b",
  "7:5": "b",
  "7:6": "b",
  "7:7": "b",

  "6:0": "b",
  "6:1": "b",
  "6:2": "b",
  "6:3": "b",
  "6:4": "b",
  "6:5": "b",
  "6:6": "b",
  "6:7": "b",
};
export const piecesOpponent = {
  "0:0": require("../assets/br.png"),
  "0:1": require("../assets/bn.png"),
  "0:2": require("../assets/bb.png"),
  "0:3": require("../assets/bk.png"),
  "0:4": require("../assets/bq.png"),
  "0:5": require("../assets/bb.png"),
  "0:6": require("../assets/bn.png"),
  "0:7": require("../assets/br.png"),

  "1:0": require("../assets/bp.png"),
  "1:1": require("../assets/bp.png"),
  "1:2": require("../assets/bp.png"),
  "1:3": require("../assets/bp.png"),
  "1:4": require("../assets/bp.png"),
  "1:5": require("../assets/bp.png"),
  "1:6": require("../assets/bp.png"),
  "1:7": require("../assets/bp.png"),

  "7:0": require("../assets/wr.png"),
  "7:1": require("../assets/wn.png"),
  "7:2": require("../assets/wb.png"),
  "7:3": require("../assets/wq.png"),
  "7:4": require("../assets/wk.png"),
  "7:5": require("../assets/wb.png"),
  "7:6": require("../assets/wn.png"),
  "7:7": require("../assets/wr.png"),

  "6:0": require("../assets/wp.png"),
  "6:1": require("../assets/wp.png"),
  "6:2": require("../assets/wp.png"),
  "6:3": require("../assets/wp.png"),
  "6:4": require("../assets/wp.png"),
  "6:5": require("../assets/wp.png"),
  "6:6": require("../assets/wp.png"),
  "6:7": require("../assets/wp.png"),
};


export const piecesOpponentConstants = {
  "0:0": "b",
  "0:1": "b",
  "0:2": "b",
  "0:3": "b",
  "0:4": "b",
  "0:5": "b",
  "0:6": "b",
  "0:7": "b",

  "1:0": "b",
  "1:1": "b",
  "1:2": "b",
  "1:3": "b",
  "1:4": "b",
  "1:5": "b",
  "1:6": "b",
  "1:7": "b",

  "7:0": "w",
  "7:1": "w",
  "7:2": "w",
  "7:3": "w",
  "7:4": "w",
  "7:5": "w",
  "7:6": "w",
  "7:7": "w",

  "6:0": "w",
  "6:1": "w",
  "6:2": "w",
  "6:3": "w",
  "6:4": "w",
  "6:5": "w",
  "6:6": "w",
  "6:7": "w",
};
