export const pieces = {
  "0:0": require("../assets/wr.png"),
  "0:1": require("../assets/wn.png"),
  "0:2": require("../assets/wb.png"),
  "0:3": require("../assets/wk.png"),
  "0:4": require("../assets/wq.png"),
  "0:5": require("../assets/wb.png"),
  "0:6": require("../assets/wn.png"),
  "0:7": require("../assets/wr.png"),

  "1:0": require("../assets/wp.png"),
  "1:1": require("../assets/wp.png"),
  "1:2": require("../assets/wp.png"),
  "1:3": require("../assets/wp.png"),
  "1:4": require("../assets/wp.png"),
  "1:5": require("../assets/wp.png"),
  "1:6": require("../assets/wp.png"),
  "1:7": require("../assets/wp.png"),

  "7:0": require("../assets/br.png"),
  "7:1": require("../assets/bn.png"),
  "7:2": require("../assets/bb.png"),
  "7:3": require("../assets/bq.png"),
  "7:4": require("../assets/bk.png"),
  "7:5": require("../assets/bb.png"),
  "7:6": require("../assets/bn.png"),
  "7:7": require("../assets/br.png"),

  "6:0": require("../assets/bp.png"),
  "6:1": require("../assets/bp.png"),
  "6:2": require("../assets/bp.png"),
  "6:3": require("../assets/bp.png"),
  "6:4": require("../assets/bp.png"),
  "6:5": require("../assets/bp.png"),
  "6:6": require("../assets/bp.png"),
  "6:7": require("../assets/bp.png"),
};

export const piecesOpponent = {
  "0:0": require("../assets/br.png"),
  "0:1": require("../assets/bn.png"),
  "0:2": require("../assets/bb.png"),
  "0:3": require("../assets/bk.png"),
  "0:4": require("../assets/bq.png"),
  "0:5": require("../assets/bb.png"),
  "0:6": require("../assets/bn.png"),
  "0:7": require("../assets/br.png"),

  "1:0": require("../assets/bp.png"),
  "1:1": require("../assets/bp.png"),
  "1:2": require("../assets/bp.png"),
  "1:3": require("../assets/bp.png"),
  "1:4": require("../assets/bp.png"),
  "1:5": require("../assets/bp.png"),
  "1:6": require("../assets/bp.png"),
  "1:7": require("../assets/bp.png"),

  "7:0": require("../assets/wr.png"),
  "7:1": require("../assets/wn.png"),
  "7:2": require("../assets/wb.png"),
  "7:3": require("../assets/wq.png"),
  "7:4": require("../assets/wk.png"),
  "7:5": require("../assets/wb.png"),
  "7:6": require("../assets/wn.png"),
  "7:7": require("../assets/wr.png"),

  "6:0": require("../assets/wp.png"),
  "6:1": require("../assets/wp.png"),
  "6:2": require("../assets/wp.png"),
  "6:3": require("../assets/wp.png"),
  "6:4": require("../assets/wp.png"),
  "6:5": require("../assets/wp.png"),
  "6:6": require("../assets/wp.png"),
  "6:7": require("../assets/wp.png"),
};
